const DEFAULT_RULE_SERVICE_BASE = "http://localhost:8080";
const DEFAULT_SEARCH_SERVICE_BASE = "http://localhost:8081";
const DEFAULT_GLOSSARY_SERVICE_BASE = "http://localhost:8000";
const DEFAULT_DATA_INGEST_SERVICE_BASE = "http://localhost:8001";

export const TOPICS_SERVICE_BASE =
  process.env.NEXT_PUBLIC_TOPICS_API ?? DEFAULT_RULE_SERVICE_BASE;

export const TEMPLATE_SERVICE_BASE =
  process.env.NEXT_PUBLIC_TEMPLATE_API ?? DEFAULT_RULE_SERVICE_BASE;

export const RUNTIME_SERVICE_BASE =
  process.env.NEXT_PUBLIC_RUNTIME_API ??
  process.env.NEXT_PUBLIC_TEMPLATE_API ??
  DEFAULT_RULE_SERVICE_BASE;

export const RULES_SERVICE_BASE =
  process.env.NEXT_PUBLIC_RUNTIME_API ??
  process.env.NEXT_PUBLIC_TEMPLATE_API ??
  process.env.NEXT_PUBLIC_TOPICS_API ??
  DEFAULT_RULE_SERVICE_BASE;

export const TAGGING_SERVICE_BASE =
  process.env.NEXT_PUBLIC_TAGGING_API ??
  process.env.NEXT_PUBLIC_TOPICS_API ??
  process.env.NEXT_PUBLIC_RUNTIME_API ??
  process.env.NEXT_PUBLIC_TEMPLATE_API ??
  DEFAULT_RULE_SERVICE_BASE;

export const ADMIN_TOPICSETS_SERVICE_BASE =
  process.env.NEXT_PUBLIC_ADMIN_API ??
  process.env.NEXT_PUBLIC_TOPICS_API ??
  DEFAULT_RULE_SERVICE_BASE;

export const REVIEWS_SERVICE_BASE =
  process.env.NEXT_PUBLIC_TOPICS_API ?? DEFAULT_RULE_SERVICE_BASE;

export const SEARCH_SERVICE_BASE =
  process.env.NEXT_PUBLIC_SEARCH_API ??
  process.env.NEXT_PUBLIC_ANALYTICS_API ??
  process.env.NEXT_PUBLIC_TAGGING_API ??
  process.env.NEXT_PUBLIC_TOPICS_API ??
  process.env.NEXT_PUBLIC_RUNTIME_API ??
  process.env.NEXT_PUBLIC_TEMPLATE_API ??
  DEFAULT_SEARCH_SERVICE_BASE;

export const ANALYTICS_SERVICE_BASE = SEARCH_SERVICE_BASE;

export const SEARCH_FACETS_SERVICE_BASE =
  process.env.NEXT_PUBLIC_SEARCH_API ??
  process.env.NEXT_PUBLIC_ANALYTICS_API ??
  process.env.NEXT_PUBLIC_RUNTIME_API ??
  process.env.NEXT_PUBLIC_TEMPLATE_API ??
  DEFAULT_SEARCH_SERVICE_BASE;

export const ANALYTICS_RUNTIME_STATUS_SERVICE_BASE =
  process.env.NEXT_PUBLIC_ADMIN_API ??
  process.env.NEXT_PUBLIC_TAGGING_API ??
  process.env.NEXT_PUBLIC_ANALYTICS_API ??
  process.env.NEXT_PUBLIC_SEARCH_API ??
  process.env.NEXT_PUBLIC_TOPICS_API ??
  process.env.NEXT_PUBLIC_RUNTIME_API ??
  process.env.NEXT_PUBLIC_TEMPLATE_API ??
  DEFAULT_RULE_SERVICE_BASE;

export const GLOSSARY_SERVICE_BASE =
  process.env.NEXT_PUBLIC_API_BASE ?? DEFAULT_GLOSSARY_SERVICE_BASE;

export const DATA_INGEST_SERVICE_BASE =
  process.env.NEXT_PUBLIC_DATA_INGEST_API ??
  DEFAULT_DATA_INGEST_SERVICE_BASE;
